# 7.2 Creating Arrays from Existing Data

In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

Multidimensional Arguments

The array function copies its argument’s dimensions. Let’s create an array from a two-row-by-three-column list:

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

NumPy auto-formats arrays, based on their number of dimensions, aligning the columns within each row.

Self Check: Create a one-dimensional array from a list comprehension that produces the even integers from 2 through 20P:

In [9]:
import numpy as np

In [10]:
one_dimensional_array = np.array([ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

In [11]:
type(one_dimensional_array)

numpy.ndarray

In [12]:
one_dimensional_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Self Check answer from book:

In [13]:
import numpy as np

In [14]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Self Check: Create a 2-by-5 array containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.

In [15]:
import numpy as np

In [18]:
Two_by_Five_array = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [19]:
type(Two_by_Five_array)

numpy.ndarray

In [20]:
Two_by_Five_array

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

# 7.3 Array Attributes

An array object provides attributes that enable you to discover information about its structure and contents.

In [21]:
import numpy as np

In [22]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [26]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

Note: NumPy does not display trailing 0s to the right of the decimal point in floating-point values.

Determining an array’s Element Type: You can check the element type with an array’s dtype attribute:

In [27]:
integers.dtype  #books displays int64, int32 on some platforms

dtype('int32')

In [28]:
floats.dtype

dtype('float64')

Determining an array’s Dimensions: The attribute ndim contains an array’s number of dimensions and the attribute shape contains a tuple specifying an array’s dimensions:

In [29]:
integers.ndim

2

In [30]:
floats.ndim

1

In [31]:
integers.shape

(2, 3)

In [32]:
floats.shape

(5,)

Determining an array’s Number of Elements and Element Size

In [33]:
integers.size

6

In [34]:
integers.itemsize ## 4 if C compiler uses 32-bit, books shows 8

4

In [35]:
 floats.size

5

In [36]:
floats.itemsize

8

Iterating Through a Multidimensional array’s Elements

In [37]:
for row in integers:
    for column in row:
        print (column, end=' ')
        print ()

1 
2 
3 
4 
5 
6 


You can iterate through a multidimensional array as if it were one-dimensional by using its flat attribute:

In [38]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

Self Check:For the two-dimensional array in the previous section’s Self Check, display the number of dimensions and shape of the array.

In [39]:
import numpy as np

In [40]:
array1 = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [41]:
array1

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [42]:
array1.ndim

2

In [43]:
array1.shape

(2, 5)

# 7.4 Filling arrays with Specific Values

NumPy provides functions zeros, ones and full for creating arrays containing  0s, 1s or a specified value, respectively. By default, zeros and ones create arrays containing float64 values. 

In [44]:
import numpy as np

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

For a tuple of integers, these functions return a multidimensional array with the specified dimensions. You can specify the array’s element type with the zeros and ones function’s dtype keyword argument:

In [46]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

The array returned by full contains elements with the second argument’s value and type:

In [47]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

# 7.5 Creating arrays from Ranges

Creating Integer Ranges with arange

NumPy’s arange function to create integer ranges—similar to using built-in function range. In each case, arange first determines the resulting array’s number of elements, allocates the memory, then stores the specified range of values in the array:

In [48]:
import numpy as np

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

Creating Floating-Point Ranges with linspace

You can produce evenly spaced floating-point ranges with NumPy’s linspace function. The function’s first two arguments specify the starting and ending values in the range, and the ending value is included in the array.

In [52]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Reshaping an array

You also can create an array from a range of elements, then use array method reshape to transform the one-dimensional array into a multidimensional array. 

In [53]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Note: You can reshape any array, provided that the new shape has the same number of elements as the original.

Displaying Large arrays

When displaying an array, if there are 1000 items or more, NumPy drops the middle rows, columns or both from the output. 

In [54]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [55]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

Self Check: Use NumPy function arange to create an array of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 array.

In [56]:
import numpy as np

In [57]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

## 7.6 List vs. array Performance: Introducing %timeit

Using the randrange function with a list comprehension to create a list of six million die rolls and time the operation using %timeit:

In [58]:
import random

In [62]:
%timeit rolls_list = \
    [random.randrange(1, 7) for i in range(0, 6_000_000)]

4 s ± 661 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Book answer differed: 6.29 s ± 119 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Now, let’s use the randint function from the numpy.random module to create an array of 6,000,000 die rolls:

In [63]:
import numpy as np

In [64]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

37.8 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Book answer differed: 72.4 ms ± 635 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

Now, let’s create an array of 60,000,000 die rolls:

In [65]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

3.98 s ± 97.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Book answer differed: 10.1 s ± 232 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Customizing the %timeit Iterations

The number of iterations within each %timeit loop and the number of loops are customizable with the -n and -r options:

In [66]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

40.6 ms ± 3.62 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


Other IPython Magics: IPython provides dozens of magics for a variety of tasks—for a complete list, see the IPython magics documentation.3 Here are a few helpful ones:

%load to read code into IPython from a local file or URL.
%save to save snippets to a file.
%run to execute a .py file from IPython.
%precision to change the default floating-point precision for IPython outputs.
%cd to change directories without having to exit IPython first.
%edit to launch an external editor—handy if you need to modify more complex snippets.
%history to view a list of all snippets and commands you’ve executed in the current IPython session.

Self Check: 

In [67]:
import numpy as np

In [68]:
sum([x for x in range(10_000_000)])
np.arange(10_000_000).sum()

-2014260032

In [70]:
%timeit sum([x for x in range(10_000_000)])

535 ms ± 16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [71]:
%timeit np.arange(10_000_000).sum()

11.6 ms ± 333 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 7.7 array Operators

Arithmetic Operations with arrays and Individual Numeric Values

In [72]:
import numpy as np

In [73]:
numbers = np.arange(1, 6)

In [74]:
numbers

array([1, 2, 3, 4, 5])

In [75]:
 numbers * 2

array([ 2,  4,  6,  8, 10])

In [76]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [77]:
numbers # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [92]:
numbers = np.arange(1, 6)

In [93]:
numbers

array([1, 2, 3, 4, 5])

In [94]:
numbers += 10

In [95]:
numbers #Augmented assignments modify every element in the left operand.

array([11, 12, 13, 14, 15])

Broadcasting

When one operand is a single value, called a scalar, NumPy performs the element-wise calculations as if the scalar were an array of the same shape as the other operand, but with the scalar value in all its elements. This is called broadcasting.

In [96]:
numbers * [2, 2, 2, 2, 2]

array([22, 24, 26, 28, 30])

Arithmetic Operations Between arrays

In [97]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [98]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [99]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

Comparing arrays

In [100]:
numbers

array([11, 12, 13, 14, 15])

In [101]:
numbers >= 13

array([False, False,  True,  True,  True])

In [102]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [103]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [104]:
numbers == numbers2

array([False, False, False, False, False])

In [105]:
numbers == numbers

array([ True,  True,  True,  True,  True])

Self Check: Create an array of the values from 1 through 5, then use broadcasting to square each value.

In [106]:
import numpy as np

In [107]:
Squared = np.arange(1, 6)

In [108]:
Squared

array([1, 2, 3, 4, 5])

In [110]:
Squared ** 2

array([ 1,  4,  9, 16, 25])

Book answer for self check:

In [111]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

## 7.8 NumPy Calculation Methods

An array has various methods that perform calculations using its contents. By default, these methods ignore the array’s shape and use all the elements in the calculations.

In [112]:
import numpy as np

In [113]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

In [114]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

We can use methods to calculate sum, min, max, mean, std (standard deviation) and var (variance)—each is a functional-style programming reduction:

In [115]:
grades.sum()

1054

In [116]:
 grades.min()

70

In [117]:
 grades.max()

100

In [118]:
grades.mean()

87.83333333333333

In [119]:
grades.std()

8.792357792739987

In [120]:
grades.var()

77.30555555555556

Calculations by Row or Column

Many calculation methods can be performed on specific array dimensions, known as the array’s axes. These methods receive an axis keyword argument that specifies which dimension to use in the calculation

In [121]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [122]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

Self Check: Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100, then reshape the result into a 3-by-4 array. Calculate the average of all the grades, the averages of the grades in each column and the averages of the grades in each row.

In [129]:
import numpy as np

In [130]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [131]:
grades

array([[77, 77, 90, 72],
       [79, 68, 90, 93],
       [91, 68, 76, 77]])

In [132]:
 grades.mean()

79.83333333333333

In [133]:
grades.mean(axis=0)

array([82.33333333, 71.        , 85.33333333, 80.66666667])

In [134]:
grades.mean(axis=1)

array([79. , 82.5, 78. ])

## 7.9 Universal Functions

NumPy offers dozens of standalone universal functions (or ufuncs) that perform various element-wise operations. Each performs its task using one or two array or array-like (such as lists) arguments.

In [135]:
import numpy as np

In [136]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [137]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

Let’s add two arrays with the same shape, using the add universal function:

In [138]:
numbers2 = np.arange(1, 7) * 10

In [139]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [140]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

Broadcasting with Universal Functions

In [141]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [142]:
numbers2 * 5

array([ 50, 100, 150, 200, 250, 300])

Let’s reshape numbers2 into a 2-by-3 array, then multiply its values by a one-dimensional array of three elements:

In [143]:
numbers3 = numbers2.reshape(2, 3)

In [144]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [145]:
numbers4 = np.array([2, 4, 6])

In [146]:
 np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

Other Universal Functions

Math—add, subtract, multiply, divide, remainder, exp, log, sqrt, power, and more.
Trigonometry—sin, cos, tan, hypot, arcsin, arccos, arctan, and more.
Bit manipulation—bitwise_and, bitwise_or, bitwise_xor, invert, left_shift and right_shift.
Comparison—greater, greater_equal, less, less_equal, equal, not_equal, logical_and, logical_or, logical_xor, logical_not, minimum, maximum, and more.

Self Check: Create an array of the values from 1 through 5, then use the power universal function and broadcasting to cube each value.

In [151]:
cat = np.arange(1, 6) ** 3

In [152]:
cat

array([  1,   8,  27,  64, 125], dtype=int32)

Book Answer for self check:

In [154]:
import numpy as np

In [ ]:
numbers = np.arange(1, 6)

In [156]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [157]:
np.power(numbers, 3) #This is how the book has the code written, but the book got the same answers as I did above not what I'm getting with the code they have

array([    1,    64,   729,  4096, 15625, 46656], dtype=int32)

## 7.10 Indexing and Slicing 

One-dimensional arrays can be indexed and sliced using the same syntax and techniques we demonstrated in the “Sequences: Lists and Tuples” chapter. 

Indexing with Two-Dimensional arrays

In [158]:
import numpy as np

In [159]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

In [160]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [161]:
grades[0, 1] # row 0, column 1

96

Selecting a Subset of a Two-Dimensional array’s Rows

To select a single row, specify only one index in square brackets:

In [162]:
grades[1]

array([100,  87,  90])

To select multiple sequential rows, use slice notation:

In [163]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

To select multiple non-sequential rows, use a list of row indices:

In [164]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

Selecting a Subset of a Two-Dimensional array’s Columns

You can select subsets of the columns by providing a tuple specifying the row(s) and column(s) to select. Each can be a specific index, a slice or a list

In [165]:
grades[:, 0]

array([ 87, 100,  94, 100])

You can select consecutive columns using a slice:

In [166]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

or specific columns using a list of column indices:

In [167]:
In [10]: grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

Self Check: Given the following array:

In [169]:
array = ([[ 1, 2, 3, 4, 5],
       [ 6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15]])

Select the second row.

In [170]:
import numpy as np

In [ ]:
array = ([[ 1, 2, 3, 4, 5],
       [ 6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15]])

In [173]:
array

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [178]:
array[1]

[6, 7, 8, 9, 10]

Select the first and third rows.

In [181]:
a = np.arange(1, 16).reshape(3, 5)

In [184]:
a[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

Select the middle three columns.

In [185]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

## 7.11 Views: Shallow Copies

The array method view returns a new array object with a view of the original array object’s data. First, let’s create an array and a view of that array:

In [186]:
import numpy as np

In [187]:
numbers = np.arange(1, 6)

In [188]:
numbers

array([1, 2, 3, 4, 5])

In [189]:
numbers2 = numbers.view()

In [190]:
numbers2

array([1, 2, 3, 4, 5])

We can use the built-in id function to see that numbers and numbers2 are different objects:

In [191]:
id(numbers)

2844621012592

In [192]:
id(numbers2)

2844620816912

To prove that numbers2 views the same data as numbers, let’s modify an element in numbers, then display both arrays:

In [193]:
numbers[1] *= 10

In [194]:
numbers2

array([ 1, 20,  3,  4,  5])

In [195]:
numbers

array([ 1, 20,  3,  4,  5])

Similarly, changing a value in the view also changes that value in the original array:

In [196]:
numbers2[1] /= 10

In [197]:
numbers

array([1, 2, 3, 4, 5])

In [198]:
numbers2

array([1, 2, 3, 4, 5])

Slice Views

In [199]:
numbers2 = numbers[0:3]

In [200]:
numbers2

array([1, 2, 3])

Again, we can confirm that numbers and numbers2 are different objects with id:

In [201]:
id(numbers)

2844621012592

In [202]:
id(numbers2)

2844621012016

Now, let’s modify an element both arrays share, then display them. Again, we see that numbers2 is a view of numbers:

In [203]:
numbers[1] *= 20

In [204]:
numbers

array([ 1, 40,  3,  4,  5])

In [205]:
 numbers2

array([ 1, 40,  3])

## 7.12 Deep Copies

when sharing mutable values, sometimes it’s necessary to create a deep copy with independent copies of the original data. 

The array method copy returns a new array object with a deep copy of the original array object’s data. First, let’s create an array and a deep copy of that array:

In [206]:
import numpy as np

In [207]:
numbers = np.arange(1, 6)

In [208]:
numbers

array([1, 2, 3, 4, 5])

In [209]:
numbers2 = numbers.copy()

In [210]:
numbers2

array([1, 2, 3, 4, 5])

To prove that numbers2 has a separate copy of the data in numbers, let’s modify an element in numbers, then display both arrays:

In [211]:
numbers[1] *= 10

In [212]:
numbers #As you can see, the change appears only in numbers.

array([ 1, 20,  3,  4,  5])

In [213]:
numbers2

array([1, 2, 3, 4, 5])

Module copy—Shallow vs. Deep Copies for Other Types of Python Objects

If you need deep copies of other types of Python objects, pass them to the copy module’s deepcopy function.

## 7.13 Reshaping and Transposing

reshape vs. resize

The array methods reshape and resize both enable you to change an array’s dimensions. Method reshape returns a view (shallow copy) of the original array with the new dimensions. It does not modify the original array:

In [214]:
import numpy as np

In [215]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [216]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [217]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [218]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

Method resize modifies the original array’s shape:

In [219]:
grades.resize(1, 6)

In [220]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

flatten vs. ravel

You can take a multidimensional array and flatten it into a single dimension with the methods flatten and ravel. Method flatten deep copies the original array’s data:

In [221]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [222]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [223]:
flattened = grades.flatten()

In [224]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [225]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

To confirm that grades and flattened do not share the data, let’s modify an element of flattened, then display both arrays:

In [226]:
flattened[0] = 100

In [227]:
flattened

array([100,  96,  70, 100,  87,  90])

In [228]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

Method ravel produces a view of the original array, which shares the grades array’s data:

In [229]:
raveled = grades.ravel()

In [230]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [231]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

To confirm that grades and raveled share the same data, let’s modify an element of raveled, then display both arrays:

In [232]:
raveled[0] = 100

In [233]:
raveled

array([100,  96,  70, 100,  87,  90])

In [234]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

Transposing Rows and Columns

The T attribute returns a transposed view (shallow copy) of the array. The original grades array represents two students’ grades (the rows) on three exams (the columns). 

In [235]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [236]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

Horizontal and Vertical Stacking

You can combine arrays by adding more columns or more rows—known as horizontal stacking and vertical stacking. 

In [237]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [238]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [239]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

Self Check: Given a 2-by-3 array: 

array([[1, 2, 3],
       [4, 5, 6]])

use hstack and vstack to produce the following array:
array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])
    

In [241]:
import numpy as np

In [242]:
a = np.arange(1, 7).reshape(2, 3)

In [243]:
a = np.hstack((a, a))

In [244]:
a = np.vstack((a, a))

In [245]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## 7.14 Intro to Data Science: pandas Series and DataFrames

See py files named project part 1 and project part 2